// Define the TypeScript interfaces for the document types and categories
export interface CategoryItem {
  id: string;
  title: string;
  description: string;
  icon: keyof typeof import("@expo/vector-icons").Ionicons.glyphMap;
}

export interface SpecificDocumentItem {
  id: string;
  title: string;
  description: string;
  category: string;
  defaultIssuer?: string;
  icon: keyof typeof import("@expo/vector-icons").Ionicons.glyphMap;
}

export const LEGAL_CATEGORIES: CategoryItem[] = [
  {
    id: "government",
    title: "Government Identification",
    description: "Passports, national IDs, driver's licenses and similar IDs",
    icon: "card-outline",
  },
  {
    id: "civil",
    title: "Civil Documents",
    description: "Birth, marriage and other civil certificates",
    icon: "document-text-outline",
  },
  {
    id: "legal",
    title: "Legal Documents",
    description: "Contracts, affidavits, permits and legal records",
    icon: "briefcase-outline",
  },
  {
    id: "financial",
    title: "Financial / Insurance",
    description: "Insurance policies and financial documents",
    icon: "wallet-outline",
  },
];

export const NON_LEGAL_CATEGORIES: CategoryItem[] = [
  {
    id: "education",
    title: "Education",
    description: "Diplomas, transcripts and certificates",
    icon: "school-outline",
  },
  {
    id: "employment",
    title: "Employment",
    description: "Employment records, certificates and IDs",
    icon: "business-outline",
  },
  {
    id: "personal",
    title: "Personal Documents",
    description: "Personal records and other documents",
    icon: "person-outline",
  },
  {
    id: "other",
    title: "Other",
    description: "Other useful documents",
    icon: "folder-outline",
  },
];

export const DOCUMENTS_BY_CATEGORY: Record<string, SpecificDocumentItem[]> = {
  government: [
    {
      id: "philippine-passport",
      title: "Philippine Passport",
      description: "Passport issued by the Department of Foreign Affairs",
      icon: "airplane-outline",
      defaultIssuer: "Department of Foreign Affairs",
      category: "passport",
    },
    {
      id: "national-id",
      title: "Philippine National ID",
      description: "PhilSys National ID",
      icon: "card-outline",
      defaultIssuer: "Philippine Statistics Authority",
      category: "government-id",
    },
    {
      id: "drivers-license",
      title: "Driver's License",
      description: "License issued by the Land Transportation Office",
      icon: "car-outline",
      defaultIssuer: "Land Transportation Office",
      category: "license",
    },
    {
      id: "prc-id",
      title: "PRC ID",
      description: "Professional identification card",
      icon: "briefcase-outline",
      defaultIssuer: "Professional Regulation Commission",
      category: "government-id",
    },
    {
      id: "sss-id",
      title: "SSS ID",
      description: "Social Security System Identification card",
      icon: "card-outline",
      defaultIssuer: "Social Security System",
      category: "government-id",
    },
    {
      id: "philhealth-id",
      title: "PhilHealth ID",
      description: "Philippine Health Insurance Corporation ID",
      icon: "medical-outline",
      defaultIssuer: "PhilHealth",
      category: "government-id",
    },
    {
      id: "tin-id",
      title: "TIN ID",
      description: "Taxpayer Identification Number card",
      icon: "document-text-outline",
      defaultIssuer: "Bureau of Internal Revenue",
      category: "government-id",
    },
    {
      id: "postal-id",
      title: "Postal ID",
      description: "Philippine Postal Corporation ID",
      icon: "mail-outline",
      defaultIssuer: "PhilPost",
      category: "government-id",
    },
    {
      id: "senior-citizen-id",
      title: "Senior Citizen ID",
      description: "Identification card for senior citizens",
      icon: "person-outline",
      defaultIssuer: "Local Government Unit / OSCA",
      category: "government-id",
    },
    {
      id: "voters-id",
      title: "Voter's ID",
      description: "Commission on Elections voter identification",
      icon: "checkbox-outline",
      defaultIssuer: "Commission on Elections",
      category: "government-id",
    },
    {
      id: "barangay-id",
      title: "Barangay ID",
      description: "Identification card issued by the local barangay",
      icon: "home-outline",
      defaultIssuer: "Barangay Hall",
      category: "government-id",
    },
    {
      id: "pwd-id",
      title: "PWD ID",
      description: "Persons with Disability identification card",
      icon: "accessibility-outline",
      defaultIssuer: "Local Government Unit / PDAO",
      category: "government-id",
    },
    {
      id: "sirb",
      title: "Seafarer’s Identification and Record Book (SIRB)",
      description: "Seaman's book issued by MARINA",
      icon: "boat-outline",
      defaultIssuer: "Maritime Industry Authority",
      category: "government-id",
    },
    {
      id: "ofw-id",
      title: "OFW ID / iDOLE Card",
      description: "Overseas Filipino Worker identification card",
      icon: "globe-outline",
      defaultIssuer: "Department of Migrant Workers",
      category: "government-id",
    },
  ],
  civil: [
    {
      id: "birth-certificate",
      title: "Birth Certificate",
      description: "Certificate of live birth",
      icon: "document-text-outline",
      defaultIssuer: "Philippine Statistics Authority",
      category: "certificate",
    },
    {
      id: "certificate-of-live-birth",
      title: "Certificate of Live Birth",
      description: "Official record of a child's birth",
      icon: "document-text-outline",
      defaultIssuer: "Philippine Statistics Authority",
      category: "certificate",
    },
    {
      id: "marriage-certificate",
      title: "Marriage Certificate",
      description: "Certificate of marriage",
      icon: "heart-outline",
      defaultIssuer: "Philippine Statistics Authority",
      category: "certificate",
    },
    {
      id: "cenomar",
      title: "CENOMAR",
      description: "Certificate of No Marriage Record",
      icon: "document-outline",
      defaultIssuer: "Philippine Statistics Authority",
      category: "certificate",
    },
    {
      id: "death-certificate",
      title: "Death Certificate",
      description: "Official record of death",
      icon: "document-text-outline",
      defaultIssuer: "Philippine Statistics Authority",
      category: "certificate",
    },
    {
      id: "certificate-of-no-death-record",
      title: "Certificate of No Death Record",
      description: "Certification verifying absence of death record",
      icon: "document-outline",
      defaultIssuer: "Philippine Statistics Authority",
      category: "certificate",
    },
    {
      id: "adoption-certificate",
      title: "Adoption Certificate",
      description: "Legal documentation of adoption",
      icon: "people-outline",
      defaultIssuer: "Philippine Statistics Authority / Court",
      category: "certificate",
    },
    {
      id: "annulment-divorce-document",
      title: "Annulment/Divorce-related Document",
      description: "Court decree or related legal document",
      icon: "file-tray-stacked-outline",
      defaultIssuer: "Regional Trial Court",
      category: "legal",
    },
  ],
  legal: [
    {
      id: "contract",
      title: "Contract",
      description: "Legal agreement or contract",
      icon: "document-text-outline",
      defaultIssuer: "",
      category: "legal",
    },
    {
      id: "affidavit",
      title: "Affidavit",
      description: "Sworn legal statement",
      icon: "document-outline",
      defaultIssuer: "",
      category: "legal",
    },
    {
      id: "deed-of-sale",
      title: "Deed of Sale",
      description: "Legal document transferring ownership of property",
      icon: "swap-horizontal-outline",
      defaultIssuer: "",
      category: "legal",
    },
    {
      id: "lease-agreement",
      title: "Lease Agreement",
      description: "Rental or property lease contract",
      icon: "home-outline",
      defaultIssuer: "",
      category: "legal",
    },
    {
      id: "spa",
      title: "Special Power of Attorney (SPA)",
      description: "Legal authorization for someone to act on your behalf",
      icon: "key-outline",
      defaultIssuer: "",
      category: "legal",
    },
    {
      id: "notarized-document",
      title: "Notarized Document",
      description: "Document bearing a notary public seal",
      icon: "ribbon-outline",
      defaultIssuer: "Notary Public",
      category: "legal",
    },
    {
      id: "court-document",
      title: "Court Document",
      description: "Official legal records from a court proceeding",
      icon: "gavel-outline" as any,
      defaultIssuer: "Judiciary / Court",
      category: "legal",
    },
    {
      id: "legal-notice",
      title: "Legal Notice",
      description: "Formal notification of a legal claim or action",
      icon: "alert-circle-outline",
      defaultIssuer: "",
      category: "legal",
    },
    {
      id: "demand-letter",
      title: "Demand Letter",
      description: "Formal letter demanding fulfillment of an obligation",
      icon: "mail-open-outline",
      defaultIssuer: "",
      category: "legal",
    },
    {
      id: "authorization-letter",
      title: "Authorization Letter",
      description: "Letter granting permission for specific actions",
      icon: "create-outline",
      defaultIssuer: "",
      category: "legal",
    },
    {
      id: "permit",
      title: "Permit",
      description: "Government or organizational permit",
      icon: "shield-checkmark-outline",
      defaultIssuer: "",
      category: "legal",
    },
    {
      id: "business-permit",
      title: "Business Permit",
      description: "Official permit to operate a business",
      icon: "business-outline",
      defaultIssuer: "Local Government Unit / City Hall",
      category: "legal",
    },
  ],
  financial: [
    {
      id: "insurance",
      title: "Insurance Policy",
      description: "Insurance policy or coverage document",
      icon: "shield-outline",
      defaultIssuer: "",
      category: "insurance",
    },
    {
      id: "insurance-claim-document",
      title: "Insurance Claim Document",
      description: "Documents related to filing an insurance claim",
      icon: "document-lock-outline",
      defaultIssuer: "",
      category: "insurance",
    },
    {
      id: "bank-document",
      title: "Bank Document",
      description: "Important banking document",
      icon: "card-outline",
      defaultIssuer: "",
      category: "financial",
    },
    {
      id: "bank-statement",
      title: "Bank Statement",
      description: "Account summary and transaction history",
      icon: "receipt-outline",
      defaultIssuer: "",
      category: "financial",
    },
    {
      id: "bank-certificate",
      title: "Bank Certificate",
      description: "Certification of deposit or account status",
      icon: "document-text-outline",
      defaultIssuer: "",
      category: "financial",
    },
    {
      id: "loan-agreement",
      title: "Loan Agreement",
      description: "Contract detailing loan terms and repayment conditions",
      icon: "cash-outline",
      defaultIssuer: "",
      category: "financial",
    },
    {
      id: "credit-card-document",
      title: "Credit Card Document",
      description: "Statements or agreement terms for credit cards",
      icon: "card-outline",
      defaultIssuer: "",
      category: "financial",
    },
    {
      id: "payment-receipt",
      title: "Payment Receipt",
      description: "Proof of payment for goods or services",
      icon: "receipt-outline",
      defaultIssuer: "",
      category: "financial",
    },
    {
      id: "tax-document",
      title: "Tax Document",
      description: "BIR returns, assessments, or tax clearances",
      icon: "calculator-outline",
      defaultIssuer: "Bureau of Internal Revenue",
      category: "financial",
    },
    {
      id: "investment-statement",
      title: "Investment Statement",
      description: "Portfolio or asset management statement",
      icon: "trending-up-outline",
      defaultIssuer: "",
      category: "financial",
    },
  ],
  education: [
    {
      id: "diploma",
      title: "Diploma",
      description: "Academic diploma",
      icon: "school-outline",
      defaultIssuer: "",
      category: "education",
    },
    {
      id: "transcript",
      title: "Academic Transcript",
      description: "Academic transcript or record",
      icon: "document-text-outline",
      defaultIssuer: "",
      category: "education",
    },
    {
      id: "report-card",
      title: "Report Card",
      description: "Periodic academic grades record",
      icon: "stats-chart-outline",
      defaultIssuer: "",
      category: "education",
    },
    {
      id: "training-certificate",
      title: "Training Certificate",
      description: "Certification of completed professional or skills training",
      icon: "ribbon-outline",
      defaultIssuer: "",
      category: "education",
    },
    {
      id: "enrollment-certificate",
      title: "Enrollment Certificate",
      description: "Proof of school enrollment or registration",
      icon: "checkmark-circle-outline",
      defaultIssuer: "",
      category: "education",
    },
    {
      id: "school-id",
      title: "School ID",
      description: "Student identification card",
      icon: "id-card-outline",
      defaultIssuer: "",
      category: "education",
    },
    {
      id: "graduation-certificate",
      title: "Graduation Certificate",
      description: "Proof of graduation from an institution",
      icon: "school-outline",
      defaultIssuer: "",
      category: "education",
    },
    {
      id: "certificate-of-completion",
      title: "Certificate of Completion",
      description: "Certificate indicating completion of a course or program",
      icon: "trophy-outline",
      defaultIssuer: "",
      category: "education",
    },
    {
      id: "scholarship-document",
      title: "Scholarship Document",
      description: "Scholarship agreement or grant terms",
      icon: "wallet-outline",
      defaultIssuer: "",
      category: "education",
    },
  ],
  employment: [
    {
      id: "employment-certificate",
      title: "Certificate of Employment",
      description: "Employment verification document",
      icon: "business-outline",
      defaultIssuer: "",
      category: "employment",
    },
    {
      id: "employment-contract",
      title: "Employment Contract",
      description: "Job terms and agreement contract",
      icon: "document-text-outline",
      defaultIssuer: "",
      category: "employment",
    },
    {
      id: "employment-id",
      title: "Company ID",
      description: "Employee identification card",
      icon: "person-outline",
      defaultIssuer: "",
      category: "employment",
    },
    {
      id: "payslip",
      title: "Payslip",
      description: "Employee salary and deduction record",
      icon: "cash-outline",
      defaultIssuer: "",
      category: "employment",
    },
    {
      id: "company-clearance",
      title: "Company Clearance",
      description: "Exit clearance document from an employer",
      icon: "checkmark-done-outline",
      defaultIssuer: "",
      category: "employment",
    },
    {
      id: "employee-certificate",
      title: "Employee Certificate",
      description: "General certification regarding employee status",
      icon: "ribbon-outline",
      defaultIssuer: "",
      category: "employment",
    },
    {
      id: "job-offer-letter",
      title: "Job Offer Letter",
      description: "Official job offer document",
      icon: "mail-open-outline",
      defaultIssuer: "",
      category: "employment",
    },
    {
      id: "resignation-letter",
      title: "Resignation Letter",
      description: "Formal letter of resignation",
      icon: "exit-outline",
      defaultIssuer: "",
      category: "employment",
    },
    {
      id: "employment-verification-letter",
      title: "Employment Verification Letter",
      description: "Letter verifying active or past employment details",
      icon: "search-outline",
      defaultIssuer: "",
      category: "employment",
    },
    {
      id: "leave-certificate",
      title: "Leave Certificate",
      description: "Approved leave or sabbatical document",
      icon: "calendar-outline",
      defaultIssuer: "",
      category: "employment",
    },
  ],
  personal: [
    {
      id: "personal-record",
      title: "Personal Record",
      description: "Personal document or record",
      icon: "person-outline",
      defaultIssuer: "",
      category: "other",
    },
    {
      id: "medical-record",
      title: "Medical Record",
      description: "Health history, prescriptions, or laboratory results",
      icon: "medkit-outline",
      defaultIssuer: "",
      category: "personal",
    },
    {
      id: "membership-card",
      title: "Membership Card",
      description: "Club, organization, or loyalty membership card",
      icon: "id-card-outline",
      defaultIssuer: "",
      category: "personal",
    },
    {
      id: "warranty-document",
      title: "Warranty Document",
      description: "Product warranty and guarantee card",
      icon: "shield-checkmark-outline",
      defaultIssuer: "",
      category: "personal",
    },
    {
      id: "property-record",
      title: "Property Record",
      description: "Land titles, tax declarations, or asset deeds",
      icon: "home-outline",
      defaultIssuer: "",
      category: "personal",
    },
    {
      id: "vehicle-registration-document",
      title: "Vehicle Registration Document",
      description:
        "LTO Certificate of Registration (CR) and Official Receipt (OR)",
      icon: "car-outline",
      defaultIssuer: "Land Transportation Office",
      category: "personal",
    },
    {
      id: "other-personal-document",
      title: "Other Personal Document",
      description: "Any other miscellaneous personal files",
      icon: "folder-outline",
      defaultIssuer: "",
      category: "personal",
    },
  ],
  other: [
    {
      id: "other",
      title: "Other Document",
      description: "A document that does not fit another category",
      icon: "folder-outline",
      defaultIssuer: "",
      category: "other",
    },
  ],
};
